// @ts-check
/**
 * Build script: reads all JSON or JSONC files from /presets/ (sorted by filename)
 * and generates src/data/presets.generated.ts.
 *
 * Usage: node scripts/build-presets.mjs
 *
 * To add a new preset:
 *   1. Create presets/NN-name.json following the PatchData v2 schema
 *   2. Run `npm run build:presets` (or let `npm run dev` do it)
 */

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const presetsDir = join(__dirname, "../presets");
const outputDir = join(__dirname, "../src/data");
const outputFile = join(outputDir, "presets.generated.ts");

// Read and sort all JSON / JSONC preset files (sorted by filename for stable ordering)
const files = readdirSync(presetsDir)
  .filter((f) => f.endsWith(".json") || f.endsWith(".jsonc"))
  .sort();

if (files.length === 0) {
  console.warn("No preset JSON files found in /presets/");
  process.exit(0);
}

const presets = files.map((filename) => {
  const content = readFileSync(join(presetsDir, filename), "utf-8");
  try {
    const stripJsonComments = (s) => s.replace(/\/\*[\s\S]*?\*\/|\/\/.*$/gm, "");
    const raw = filename.endsWith(".jsonc") ? stripJsonComments(content) : content;
    return JSON.parse(raw);
  } catch (e) {
    console.error(`Failed to parse ${filename}:`, e.message);
    process.exit(1);
  }
});

// Ensure output directory exists
mkdirSync(outputDir, { recursive: true });

const output = `// THIS FILE IS AUTO-GENERATED by scripts/build-presets.mjs — DO NOT EDIT DIRECTLY.
// To add or modify presets, edit the JSON files in /presets/ and re-run \`npm run build:presets\`.
import type { PatchData } from "@/patch/schema";

export const FACTORY_PRESETS: PatchData[] = ${JSON.stringify(presets, null, 2)};
`;

writeFileSync(outputFile, output, "utf-8");
console.log(`[build-presets] ${presets.length} presets → src/data/presets.generated.ts`);
